name: projeto-ia
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.1
  - numpy=1.26.4
  - scikit-learn=1.4.2
  - xgboost=2.0.3
  - imbalanced-learn=0.12.0
  - notebook
  - jupyterlab
  - matplotlib
  - seaborn
  - pip
  - pip:
    - jupyter_contrib_nbextensions
