name: projeto-ia
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - ipykernel
  - pip
  - pip:
      - imbalanced-learn
